# Crucial for TCP Window Scaling to achieve high throughput
net.ipv4.tcp_timestamps=1
net.ipv4.tcp_sack=1

# Enable the TCP selective acks option for better throughput:
net.ipv4.tcp_sack=1

# Handles high volumes of incoming packets to prevent drops at the NIC layer
net.core.netdev_max_backlog=250000

# Increase the TCP maximum and default buffer sizes using setsockopt():
net.core.rmem_default=4194304
net.core.wmem_default=4194304

# Allows the kernel to allocate large buffers for high-bandwidth connections
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.core.optmem_max = 4194304

# Increase memory thresholds to prevent packet dropping:
net.ipv4.tcp_rmem="4096 87380 16777216"
net.ipv4.tcp_wmem="4096 65536 16777216"

# Enable low latency mode for TCP:
net.ipv4.tcp_low_latency=1

# Controls window sizing vs application buffer (1 = even split)
net.ipv4.tcp_adv_win_scale=1

# Maximizes the number of incoming connection attempts allowed in the queue
net.core.somaxconn = 65535

# Speeds up recycling of closed connections to prevent port exhaustion can cause issues
# net.ipv4.tcp_fin_timeout = 15